application: account
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/(.*)
  static_files: static/\1

- url: /.*
  wsgi_app: app:app

daemons:
- name: testdaemon1
  num_instances: 1
  script: testdaemon1.py --verbose -u test
  mem_limit: 64M
